Repository saidmsaif/indeat-food-delivery-template-tailwindcss, pull requests merged in 2021-08, with the labels that each got.

#32 restaurent by cities page sidebar
  assets/css/custom.css
  restaurant-by-cities.html
Labels: Finishing Design

#34 about us page design
  About-us.html
  assets/css/custom.css
  assets/images/about-hero-bg.jpg
  assets/images/about-hero-bg.png
  assets/images/cms-hero 1.jpg
  assets/images/cms-hero 1.png
  assets/images/cms-hero-bg 1.png
  assets/images/privacy.png
  assets/images/terms.png
  assets/images/wallpaper (1600x400) 3 (3).png
  privacy-policy.html
  resturent-single-page-by-cities.html
  terms-and-condition.html
Labels: Design in progress

#39 Check
  About-us.html
  assets/css/custom.css
  assets/css/style.css
  assets/images/cms-hero1.jpg
  assets/images/cms-hero1.png
  assets/images/svg.svg
  login-page-1st-step.html
  login-page-2nd-step.html
  login-page-3rd-step.html
  tailwind.config.js
  webshop-for-indeat-partner.html
Labels: Finished

#40 about us page design fix
  About-us.html
  my-profile.html
Labels: Finished

#41 icon responsiveness fix
  About-us.html
  my-profile.html
  webshop-for-indeat-partner.html
Labels: Finished

#42 Check
  assets/css/custom.css
Labels: Finished

#43 my portfoliyo page only header section (done)
  my-profile.html
Labels: In progress

#44 Rasel
  my-profile.html
Labels: Finished
